### ISSUE TITLE
cli not working

### ISSUE THREAD

**Issue by carlosperezc** [alivx/revealjs-digital-signage#13]
Hello, I tried to use curl to rollover the slides but they never move to the next:

curl http://localhost:5000/next

just prints next but nothing more.

i got a message from the logs tho: The client is using an unsupported version of the Socket.IO or Engine.IO protocols

**Comment by carlosperezc** [comment]
there was mismatch version with socketio.js. I updated the version to v4.1.3 and it works.

**Comment by alivx** [comment]
> there was mismatch version with socketio.js. I updated the version to v4.1.3 and it works.

Cloud you please create pull request for that change, :)
